config/routes.rb
Rails.application.routes.draw do
  # Subscriptions
  get "subscriptions/new", to: "subscriptions#new", as: "new_subscription"
  get "subscriptions/checkout", to: "subscriptions#checkout", as: "checkout"

  # Onboarding
  get "onboarding", to: "onboarding#index"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"

  # Devise
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  devise_scope :user do
    unauthenticated do
      root to: "static_pages#index"
    end

    authenticated do
      root to: "dashboard#index", as: :authenticated_root
    end
  end

  # Good Job admin dashboard
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    ### Everything below this line requires login ###
    return unless user.present?

    ### Admin permissions ###
    return unless user.admin? # Admin can do everything above, plus everything below

    can :show, :admin_dashboard
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  self.implicit_order_column = :created_at
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer default_payment_processor: :stripe, stripe_attributes: :stripe_attributes

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :confirmable, :lockable, :trackable

  attr_accessor :terms_and_conditions

  validates :first_name, :last_name, presence: true
  validates_acceptance_of :terms_and_conditions, allow_nil: false, on: :create
  validate :uncommon_password

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def uncommon_password
    # Checks password against a wordlist of common passwords
    return if password.blank?

    if COMMON_PASSWORDS.include?(password)
      errors.add(:password, "Cannot be a common password")
    end
  end


  private

  def stripe_attributes(pay_customer)
    {
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id
      }
    }
  end

  def pay_should_sync_customer?
    super || saved_change_to_first_name? || saved_change_to_last_name?
  end

  def send_devise_notification(notification, *)
    devise_mailer.send(notification, self, *).deliver_later(queue: :devise)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def require_admin
    return if current_user.admin?
    redirect_to root_path, notice: "You must be an admin to access this resource"
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :terms_and_conditions])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def require_turbo_frame_request
    head :unauthorized unless turbo_frame_request?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # layout "application2"

  def index
  end
end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController
  before_action :require_turbo_frame_request

  def index
    session[:onboarding] = nil # Remove modal as soon as the first screen has been seen by the user
  end

  def confirm_email
  end

  def organisation
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  layout "landing_page"

  def index
  end

  def privacy
  end

  def terms
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:pricing]
  layout "landing_page"

  def index
    # Render a users billing portal
    @portal_session = current_user.payment_processor.billing_portal
  end

  def new
  end

  def checkout
    if params[:price_id]
      # Make sure the user's payment processor is Stripe
      current_user.set_payment_processor :stripe

      # Build checkout session with price
      @checkout_session = current_user.payment_processor.checkout(
        mode: "subscription",
        locale: I18n.locale,
        allow_promotion_codes: true,
        line_items: [{
          price: params[:price_id],
          quantity: 1
        }],
        success_url: root_url,
        cancel_url: subscriptions_new_url,
        automatic_tax: {enabled: true},
        customer_update: {address: "auto"}
      )

      # Redirect to checkout
      redirect_to @checkout_session.url, allow_other_host: true, status: :see_other
    else
      redirect_to root_path, alert: "Something went wrong, please try again"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    # Attempt to cancel subscription (if one exists) on account deletion
    subscription = resource.payment_processor.subscription
    subscription.cancel_now! if subscription

    # Destroy the user as normal
    super
  end

  private

  def after_sign_up_path_for(resource)
    session[:onboarding] = true
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def error_message_on(object, attribute)
    return unless object.respond_to?(:errors) && object.errors.include?(attribute)

    error_message = "#{attribute.to_s.humanize} #{object.errors[attribute].join(", ")}"

    content_tag(:div, class: "flex items-center text-red-600 text-xs mt-2") do
      content_tag(:i, nil, class: "fa-solid fa-circle-exclamation inline mr-1") + error_message
    end
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_css_class(key)
    case key.to_sym
    when :alert
      "bg-red-100 text-red-700"
    when :notice
      "bg-green-100 text-green-700"
    else
      "bg-blue-100 text-blue-700"
    end
  end
end

app/views/dashboard/_onboarding_modal.html.erb
<% if session[:onboarding] %>
  <div data-controller="modal confetti" data-modal-open-on-connect-value="true" data-action="load@window->confetti#cannon">
    <%= render "shared/modal" do %>
      <%= turbo_frame_tag "onboarding", src: onboarding_path %>
    <% end %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<h1 class="text-3xl font-semibold">Welcome back <%= current_user.first_name %></h1>
<hr class="my-6">

<%= render "dashboard/onboarding_modal" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Boilerplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'favicon.ico', "data-turbo-track": "reload" %>
    <%= render "shared/metatags" %>
    <%= render "shared/analytics" %>
  </head>

  <body class="bg-zinc-50 text-zinc-800">
    <%= render "shared/flash_notifications" %>

    <main class="min-h-screen flex w-full" data-controller="reveal">
      <%= render "shared/sidebar" %>

      <div class="flex flex-col bg-zinc-50 w-full">
        <%= render "shared/application_navigation" %>

          <%= render "shared/subscription_banner" %>

        <div class="p-6 h-full">
          <%= yield %>
        </div>
      </div>

      <%= render "shared/feedback_widget" %>
    </main>
  </body>
</html>

app/views/layouts/blog_post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boilerplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'favicon.ico', "data-turbo-track": "reload" %>
    <%= render "shared/metatags" %>
    <%= render "shared/analytics" %>
  </head>

  <body>

    <article class="px-4 py-24 mx-auto max-w-7xl" itemid="#" itemscope itemtype="http://schema.org/BlogPosting">
      <div class="w-full mx-auto mb-12 text-center md:w-2/3">
        <p class="mb-3 text-xs font-semibold tracking-wider text-gray-500 uppercase">Development</p>
        <h1 class="mb-3 text-4xl font-bold text-gray-900 md:leading-tight md:text-5xl" itemprop="headline" title="Rise of Tailwind - A Utility First CSS Framework">
          Rise of Tailwind - A Utility First CSS Framework
        </h1>
        <p class="text-gray-700">
        Written by
        <span class="byline author vcard" itemprop="author" itemscope="itemscope" itemtype="http://schema.org/Person">
          <a href="#" target="_blank" itemprop="url" rel="author noopener noreferrer" class="text-primary hover:text-primary-dark"><span itemprop="name">Praveen Juge</span></a>
        </span>
        on <time itemprop="datePublished dateModified" datetime="2010-08-07 11:11:03-0400" pubdate>Jan 02 2021</time>
        </p>
      </div>

      <div class="mx-auto prose">
        <p>
        What if there is an easy way to achieve responsive UI without using any UI kit? Can we create new and fresh designs for every project with a CSS framework? Enter Tailwind CSS, will this be the
        perfect CSS framework, well let’s find out.
        </p>
        <p>Tailwind is a utility-first CSS framework, the keyword being ‘utility’. It is basically a set of classes that you can use in your HTML.</p>
        <pre>
.bg-purple-700 {
  background-color: #6b46c1;
}

.px-4 {
  padding-top: 1rem;
  padding-bottom: 1rem;
}</pre
        >
        <p>
        Therefore, we don’t have to write any custom CSS to get this button. This can be heavily extended to build whole web applications without the need for any other styles apart from a tailwind.
        </p>
        <p>...</p>
      </div>
    </article>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Boilerplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'favicon.ico', "data-turbo-track": "reload" %>
    <%= render "shared/metatags" %>
    <%= render "shared/analytics" %>
  </head>

  <body class="bg-zinc-100 text-zinc-900">
    <%= render "shared/flash_notifications" %>

    <div class="md:flex md:min-h-screen">
      <div class="flex flex-col md:rounded-3xl w-full">
        <%= link_to root_path, class: "text-center pt-6 text-xl font-semibold cursor-pointer" do %>
          Boilerplate
        <% end %>

        <div class="md:flex md:flex-col h-full md:justify-center md:items-center p-6">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Boilerplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'favicon.ico', "data-turbo-track": "reload" %>
    <%= render "shared/metatags" %>
    <%= render "shared/analytics" %>
  </head>

  <body class="bg-zinc-50 text-zinc-800">
    <%= render "shared/flash_notifications" %>

    <main class="min-h-screen">
      <div class="bg-zinc-50 sticky top-0 z-10">
        <%= render "shared/navigation" %>
      </div>

      <%= yield %>
    </main>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/onboarding/index.html.erb
<%= turbo_frame_tag "onboarding" do %>
  <div class="flex flex-col items-center">
    <h1 class="text-2xl font-semibold">Welcome to Boilerplate 👋</h1>
    <p class="my-8">
      This is an onboarding modal. You can use it to prompt users to set up their account, confirm their email, or direct them to somewhere useful.
    </p>
    <%= link_to "Got it!", root_path, class: "px-8 py-2 bg-slate-900 text-white rounded-xl" %>
  </div>
<% end %>

app/views/shared/_application_navigation.html.erb
<div class="w-full p-6">
  <div class="flex justify-between items-center gap-6">
    <div>
      <div class="hidden lg:block">
        <a href="#" data-reveal-target="openTrigger" data-action="click->reveal#toggle:prevent" class="hidden h-12 w-12 bg-slate-200 hover:bg-slate-300 rounded-lg flex items-center justify-center cursor-pointer" aria-label="Open sidebar">
          <i class="fa-solid fa-angles-right text-slate-900"></i>
        </a>
      </div>

      <a href="#" class="lg:hidden h-12 w-12 bg-slate-200 hover:bg-slate-300 rounded-lg flex items-center justify-center cursor-pointer" aria-label="Toggle mobile navigation">
        <i class="fa-solid fa-bars text-slate-900"></i>
      </a>
    </div>

    <div class="flex justify-between items-center gap-6">
      <%= link_to edit_user_registration_path, class: "h-12 w-12 bg-slate-200 hover:bg-slate-300 rounded-lg flex items-center justify-center cursor-pointer" do %>
        <i class="fa-solid fa-gear text-2xl text-slate-900"></i>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "cursor-pointer hover:underline" do %>
        <i class="fa-solid fa-arrow-right-from-bracket mr-1.5"></i>Log out
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="px-6">
  <div class="bg-indigo-500 py-3 text-white rounded-xl">
    <p class="text-left text-sm font-medium sm:text-center">
      Love Alpine JS? Check out this new course!

      <a class="underline" href="/alpinejs"> Learn More &rarr; </a>
    </p>
  </div>
</div>

app/views/shared/_feedback_widget.html.erb
<%= mail_to(Rails.application.credentials.mailer.support_email) do %>
  <div class="fixed bottom-1/4 right-2 flex items-center justify-center bg-green-600 hover:bg-green-700 h-14 w-14 rounded-xl animate__animated animate__tada">
    <i class="fa-regular fa-comment fa-xl text-zinc-50"></i>
  </div>
<% end %>

app/views/shared/_flash_notifications.html.erb
<% flash.each do |key, value| %>
  <div data-controller="flash" class="flex items-center fixed top-3 right-3 z-50 <%= flash_css_class(key) %> p-5 rounded-lg shadow-md">
    <div class="mr-4"><%= value %></div>

    <button type="button" data-action="flash#dismiss">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="w-full bg-zinc-50 text-zinc-900 border-t">
  <div class="container mx-auto px-4 py-10">
    <div class="grid grid-cols-2 gap-10 mb-3 md:grid-cols-6">
      <div class="col-span-2">
        <%= link_to "Boilerplate", root_path, class: "text-xl font-semibold" %>

        <p class="my-4 text-zinc-500">
          Put a nice short description of your app here. Built by @spencerldixon
        </p>
      </div>

      <nav class="flex flex-col gap-2 col-span-1">
        <p class="font-semibold">Features</p>
        <%= link_to "Features", "#features", class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Pricing", "#pricing", class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Feedback", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "FAQs", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
      </nav>

      <nav class="flex flex-col gap-2 col-span-1">
        <p class="font-semibold">Support</p>
        <%= link_to "Chat", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Email", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "GDPR", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Help", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
      </nav>

      <nav class="flex flex-col gap-2 col-span-1">
        <p class="font-semibold">Resources</p>
        <%= link_to "Blog", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Twitter", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Alternatives", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Why", root_path, class: "hover:underline decoration-2 underline-offset-4" %>
      </nav>

      <nav class="flex flex-col gap-2 col-span-1">
        <p class="font-semibold">Legal</p>
        <%= link_to "Privacy", privacy_path, class: "hover:underline decoration-2 underline-offset-4" %>
        <%= link_to "Terms", terms_path, class: "hover:underline decoration-2 underline-offset-4" %>
      </nav>
    </div>

    <div class="flex flex-row items-baseline justify-between mt-10">
      <p class="text-zinc-500 mb-4 md:mb-0 text-sm">Copyright <%= Date.current.year %></p>

      <div class="flex text-zinc-800 gap-x-4">
        <%= link_to root_path do %>
          <i class="fa-brands fa-github fa-xl"></i>
        <% end %>

        <%= link_to root_path do %>
          <i class="fa-brands fa-twitter fa-xl"></i>
        <% end %>

        <%= link_to root_path do %>
          <i class="fa-brands fa-discord fa-xl"></i>
        <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_metatags.html.erb
<meta name="description" content="A mildly opinionated Rails 7 SaaS boilerplate">
<meta name="keywords" content="HTML, CSS, JavaScript">

app/views/shared/_mobile_overlay.html.erb
<nav class="hidden bg-white h-screen w-screen fixed top-0 left-0 animate__animated animate__slideInLeft animate__faster z-20 overflow-auto" data-reveal-target="hideable">
  <div class="container">
    <%= render "shared/sidebar" %>
  </div>
</nav>

app/views/shared/_modal.html.erb
<div class="flex fixed top-0 left-0 z-20 bg-neutral-500/50 h-screen w-screen justify-center items-center hidden" data-modal-target="modal" data-action="keydown.esc@window->modal#close click->modal#close">
  <div class="bg-white z-50 m-4 max-w-xl rounded-2xl drop-shadow-2xl min-w-[20%] overflow-auto">
    <i id="close_modal" class="fixed top-4 right-4 fa-solid fa-xmark fill-neutral-900 h-4 w-4 cursor-pointer" data-action="click->modal#close"></i>

    <div class="overflow-auto max-h-[80vh] p-6">
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="w-full">
  <div class="container mx-auto p-4">
    <div class="flex justify-between items-center">
      <div class="flex items-center">
        <%= link_to root_path, class: "text-xl font-semibold cursor-pointer" do %>
          Boilerplate
        <% end %>

        <div class="ml-12 hidden md:flex justify-center items-center font-semibold gap-6">
          <% unless user_signed_in? %>
            <%= link_to "Features", "#features", class: "hover:underline decoration-2 underline-offset-8" %>
            <%= link_to "Pricing", "#pricing", class: "hover:underline decoration-2 underline-offset-8" %>
            <%= link_to "Blog", root_path, class: "hover:underline decoration-2 underline-offset-8" %>
          <% end %>
        </div>
      </div>

      <div class="flex justify-end items-center gap-6">
        <% if user_signed_in? %>
          <%= link_to edit_user_registration_path, class: "h-12 w-12 bg-gray-200 rounded-lg flex items-center justify-center cursor-pointer" do %>
            <i class="fa-solid fa-gear text-2xl text-gray-900"></i>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "cursor-pointer hover:underline" do %>
            <i class="fa-solid fa-arrow-right-from-bracket mr-1.5"></i>Log out
          <% end %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "hover:underline decoration-2 underline-offset-8 cursor-pointer" %>
          <%= link_to new_user_registration_path, class: "px-4 py-2 bg-zinc-900 hover:bg-zinc-700 text-zinc-50 rounded-lg" do %>
            Sign up for free <i class="fa-solid fa-arrow-right ml-2"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="hidden lg:flex flex-col bg-white w-[24rem] shrink-0 p-6" data-reveal-target="hideable" data-reveal-hidden-class-value="lg:flex">
  <div class="flex justify-between items-center mb-6">
    <%= link_to root_path, class: "text-xl font-semibold cursor-pointer" do %>
      Boilerplate
    <% end %>

    <a href="#" data-reveal-target="closeTrigger" data-action="click->reveal#toggle:prevent" class="h-12 w-12 bg-slate-200 hover:bg-slate-300 rounded-lg flex items-center justify-center cursor-pointer" aria-label="Close sidebar">
      <i class="fa-solid fa-angles-left text-slate-900"></i>
    </a>
  </div>

  <div class="flex flex-col gap-2">
    <%= active_link_to root_path, class: "hover:bg-slate-200 flex py-3 px-6 rounded-lg", class_active: "bg-slate-100" do %>
      Dashboard
    <% end %>

    <%= link_to root_path, class: "hover:bg-slate-200 flex py-3 px-6 rounded-lg" do %>
      Something
    <% end %>

    <% if can? :show, :admin_dashboard %>
      <%= link_to root_path, class: "hover:bg-slate-200 flex py-3 px-6 rounded-lg" do %>
        Admin
      <% end %>
    <% end %>

    <%= link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "cursor-pointer hover:underline py-3 px-6" do %>
      <i class="fa-solid fa-arrow-right-from-bracket mr-1.5"></i>Log out
    <% end %>
  </div>
</div>

app/views/shared/_subscription_banner.html.erb
<% unless current_user.payment_processor.subscribed? %>
  <div id="subscription-banner" class="flex bg-indigo-500 text-white font-semibold p-2 justify-center rounded-xl">
    You do not have an active subscription. <%= link_to "Subscribe now", new_subscription_path, class: "font-bold underline", data: { turbo: false } %>
  </div>
<% end %>

app/views/static_pages/_cta.html.erb
<section class="w-full">
  <div class="w-full px-4 py-20 mx-auto text-left md:text-center md:w-3/4 lg:w-2/4">


      <h1 class="block pb-2 mb-5 text-4xl font-extrabold leading-none tracking-normal text-transparent md:text-6xl md:tracking-tight bg-clip-text bg-gradient-to-r from-amber-200 to-amber-600">
        Simple, transparent pricing.
      </h1>
    <h2 class="mb-6 text-3xl font-extrabold md:text-4xl md:mb-6 md:leading-tight">Start a free trial with 10 API credits<br> No credit card required</h2>

      <div class="my-12">
        <%= link_to new_user_registration_path, class: "px-8 py-4 rounded-lg bg-zinc-900 text-zinc-50 text-lg" do %>
          Sign up for free <i class="fa-solid fa-arrow-right ml-2"></i>
        <% end %>
      </div>

    <p class="text-base font-semibold text-amber-600">Start your free trial now</p>



    </div>
  </div>
</section>

app/views/static_pages/_feature.html.erb
<section id="features" class="p-4">
  <div class="container mx-auto bg-zinc-100 rounded-3xl grid lg:grid-cols-2 p-8 lg:p-12 xl:p-24 gap-8">
    <div class="my-auto">
      <h2 class="mb-8 text-5xl font-extrabold md:text-6xl md:tracking-tight">
        All your <span class="block w-full text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-amber-600 lg:inline">boilerplate</span> are belong to us.
      </h2>

      <p class="text-xl">
        Boilerplate is a mildly opinionated Rails starter app built on Rails, PostgreSQL, Stimulus and TailwindCSS.
      </p>
    </div>

    <div class="lg:mx-auto">
      <%= image_tag "https://placehold.co/600x400/orange/white", class: "rounded-xl md:rounded-3xl w-full" %>
    </div>
  </div>
</section>

app/views/static_pages/_feature_d.html.erb
<div class="p-4">
  <div class="container mx-auto bg-zinc-100 rounded-3xl grid lg:grid-cols-2 px-8 lg:px-12 xl:px-24 gap-12 overflow-hidden p-8 lg:p-0">
    <div class="lg:mx-auto">
      <div class="grid grid-cols-2 gap-4">
        <div class="grid gap-4 rotate-2">
          <img class="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image.jpg" alt="">
          <img class="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-1.jpg" alt="">
        </div>
        <div class="grid gap-4 items-center rotate-2">
          <img class="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-4.jpg" alt="">
        </div>
      </div>
    </div>

    <div class="my-auto">
      <h2 class="mb-8 text-5xl font-extrabold md:text-6xl md:tracking-tight">
        All your <span class="block w-full text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-amber-600 lg:inline">boilerplate</span> are belong to us.
      </h2>

      <p class="text-xl">
        Boilerplate is a mildly opinionated Rails starter app built on Rails, PostgreSQL, Stimulus and TailwindCSS.
      </p>
    </div>
  </div>
</div>

app/views/subscriptions/checkout.html.erb
<h1>Subscriptions#checkout</h1>
<p>Find me in app/views/subscriptions/checkout.html.erb</p>